import type { ReactNode } from 'react'
import { Button } from './ui'

export function PrintButton({ label = 'Print' }: { label?: string }) {
  return (
    <Button variant="secondary" onClick={() => window.print()}>
      <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8">
        <path d="M6 9V3h12v6M6 18H4a2 2 0 01-2-2v-5a2 2 0 012-2h16a2 2 0 012 2v5a2 2 0 01-2 2h-2M6 14h12v7H6z" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
      {label}
    </Button>
  )
}

export interface PrintSheetMeta {
  label: string
  value: string
}

export function PrintSheet({
  title,
  number,
  subtitle,
  meta,
  columns,
  rows,
  footer,
}: {
  title: string
  number?: string
  subtitle?: string
  meta?: PrintSheetMeta[]
  columns: string[]
  rows: ReactNode[][]
  footer?: ReactNode
}) {
  return (
    <div className="print-sheet hidden">
      <div className="mx-auto max-w-[740px] bg-white px-10 py-8 text-slate-900">
        <div className="flex items-start justify-between border-b-2 border-emerald-800 pb-4">
          <div>
            <p className="text-lg font-bold text-emerald-900">GRS IPS</p>
            <p className="text-xs text-slate-500">Purchase Management System</p>
          </div>
          <div className="text-right">
            <p className="text-xl font-bold uppercase tracking-wide text-slate-900">{title}</p>
            {number && (
              <p className="font-mono text-sm font-semibold text-emerald-800">{number}</p>
            )}
          </div>
        </div>

        {subtitle && <p className="mt-3 text-sm text-slate-600">{subtitle}</p>}

        {meta && meta.length > 0 && (
          <div className="mt-4 grid grid-cols-2 gap-x-8 gap-y-1.5 text-sm">
            {meta.map((m, i) => (
              <div key={i} className="flex items-baseline justify-between gap-4 border-b border-dashed border-slate-200 pb-1">
                <span className="shrink-0 text-slate-500">{m.label}</span>
                <span className="text-right font-medium">{m.value}</span>
              </div>
            ))}
          </div>
        )}

        <table className="mt-5 w-full border-collapse text-sm">
          <thead>
            <tr>
              {columns.map((c, i) => (
                <th
                  key={i}
                  className="border-b-2 border-emerald-800 px-2 py-1.5 text-left text-xs font-semibold uppercase tracking-wide text-emerald-900"
                >
                  {c}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row, i) => (
              <tr key={i}>
                {row.map((cell, j) => (
                  <td key={j} className="border-b border-slate-200 px-2 py-1.5 align-top">
                    {cell}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>

        {footer && <div className="mt-2 text-sm">{footer}</div>}

        <div className="mt-12 grid grid-cols-2 gap-10 text-sm">
          <div>
            <p className="text-[10px] uppercase tracking-widest text-slate-400">Prepared by</p>
            <div className="mt-8 border-b border-slate-400" />
          </div>
          <div>
            <p className="text-[10px] uppercase tracking-widest text-slate-400">Authorised signatory</p>
            <div className="mt-8 border-b border-slate-400" />
          </div>
        </div>

        <p className="mt-8 text-center text-[10px] text-slate-400">
          Generated by GRS IPS Purchase Management on {new Date().toLocaleString()}
        </p>
      </div>
    </div>
  )
}
